# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-25 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20170425_0232'),
        ('config', '0002_auto_20170403_1239'),
    ]

    operations = [
    ]
