# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-25 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20170403_1239'),
        ('exercises', '0004_auto_20170425_1513'),
    ]

    operations = [
    ]
