# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-28 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecomment',
            name='exercise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise', verbose_name='Exercise'),
        ),
    ]
