# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-28 13:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Amount'),
        ),
    ]
