# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170425_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='test_field',
            field=models.CharField(default='String', max_length=200),
        ),
    ]
