# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-25 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_apiuser_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='test_field',
        ),
    ]
