# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-25 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20160429_1613'),
        ('manager', '0008_auto_20170403_1239'),
    ]

    operations = [
    ]
